resources:
  - name: git-demo-redux-repo
    type: git
    source:
      uri: git@github.com:tanvirpathan/redux-example.git
      branch: master
      private_key: ((github-private-key))

jobs:
  - name: test-demo-redux
    plan:
      - get: git-demo-redux-repo
        trigger: true
      - task: test
        input_mapping:
          demo-redux-repo: git-demo-redux-repo
        # file: git-demo-redux-repo/test.yml
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: '8-alpine'
          inputs:
            - name: demo-redux-repo
          caches:
            - path: demo-redux-repo/node_modules
          run:
            path: sh
            args:
            - -exc
            - |
              pwd
              ls
              cd demo-redux-repo
              ls
              yarn install --no-progress
              yarn lint
              CI=true yarn test

        params:
          NODE_ENV: test

# jobs:
#   - name: hello-world
#     plan:
#       - get: git-demo-redux-repo
#         trigger: true
#       - task: say-hello
#         config:
#           platform: linux
#           image_resource:
#             type: docker-image
#             source: {repository: ubuntu}
#           run:
#             path: echo
#             args: ["Hello, world!"]
