resources:
  - name: git-demo-redux-repo
    type: git
    source:
      uri: git@github.com:tanvirpathan/redux-example.git
      branch: master
      private_key: ((github-private-key))
  - name: cf-dev
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: ((cf-username))
      password: ((cf-password))
      organization: ((cf-org))
      space: ((cf-dev-space))

jobs:
  - name: test-demo-redux
    plan:
      - get: git-demo-redux-repo
        trigger: true
      - task: test
        input_mapping:
          demo-redux-repo: git-demo-redux-repo
        file: git-demo-redux-repo/test.yml
        params:
          NODE_ENV: test
  - name: deploy-cf-demo-redux
    plan:
      - get: git-demo-redux-repo
        trigger: true
        passed: [test-demo-redux]
      - task: build
        input_mapping:
          demo-redux-repo: git-demo-redux-repo
        file: git-demo-redux-repo/build.yml
        params:
          MANIFEST: manifest_dev.yml
          PUBLIC_URL: /
          REACT_APP_GA: UA-32916794-3
      - put: cf-dev
        params:
          manifest: build/manifest_dev.yml
          path: build
          current_app_name: demo-redux
