resources:
  - name: git-demo-redux-repo
    type: git
    source:
      uri: git@github.com:tanvirpathan/redux-example.git
      branch: master
      private_key: ((github-private-key))

jobs:
  - name: test-demo-redux
    plan:
      - get: git-demo-redux-repo
        trigger: true
      - task: test
        input_mapping:
          demo-redux-repo: git-demo-redux-repo
        file: test.yml
        params:
          NODE_ENV: test

# jobs:
#   - name: hello-world
#     plan:
#       - get: git-demo-redux-repo
#         trigger: true
#       - task: say-hello
#         config:
#           platform: linux
#           image_resource:
#             type: docker-image
#             source: {repository: ubuntu}
#           run:
#             path: echo
#             args: ["Hello, world!"]
