resources:
  - name: git-demo-redux-repo
    type: git
    source:
      uri: git@github.com:tanvirpathan/redux-example.git
      branch: master
      private_key: ((github-private-key))
  - name: cf-dev
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: ((cf-username))
      password: ((cf-password))
      organization: ((cf-org))
      space: ((cf-dev-space))
  - name: git-pr-demo-react
    type: pull-request
    source:
      access_token: ((github-access-token))
      private_key: ((github-private-key))
      uri: git@github.com:tanvirpathan/redux-example.git
      repo: tanvirpathan/redux-example
      base: master
resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: jtarchie/pr
jobs:
  - name: test-demo-redux
    plan:
      - get: git-demo-redux-repo
        trigger: true
      - task: test
        input_mapping:
          demo-redux-repo: git-demo-redux-repo
        file: git-demo-redux-repo/test.yml
        params:
          NODE_ENV: test
  - name: deploy-cf-demo-redux
    plan:
      - get: git-demo-redux-repo
        trigger: true
        passed: [test-demo-redux]
      - task: build
        input_mapping:
          demo-redux-repo: git-demo-redux-repo
        file: git-demo-redux-repo/build.yml
        params:
          MANIFEST: manifest_dev.yml
          PUBLIC_URL: /
          REACT_APP_GA: UA-32916794-3
      - put: cf-dev
        params:
          manifest: build/manifest_dev.yml
          path: build
          current_app_name: demo-redux
  - name: test-web-pr
    plan:
      - get: git-pr-demo-react
        trigger: true
      - task: test
        input_mapping:
          pr-demo-react: git-pr-demo-react
        file: git-pr-demo-react/test.yml
        params:
          NODE_ENV: test
        on_success:
          put: git-pr-demo-react
          params:
            path: git-pr-demo-react
            status: success
        on_failure:
          put: git-pr-demo-react
          params:
            path: git-pr-demo-react
            status: failure
